// Auto-generated by scripts/rmlui-bindgen — DO NOT EDIT
// Source: packages/types/src/rmlui-abi.h

// ── Raw @external Imports ──────────────────────────────────────────

@external("env", "Rml_CreateContext")
export declare function rawRml_CreateContext(name: string, w: i32, h: i32): i32;

@external("env", "Rml_ReleaseContext")
export declare function rawRml_ReleaseContext(ctx: i32): void;

@external("env", "Rml_LoadDocument")
export declare function rawRml_LoadDocument(ctx: i32, path: string): i32;

@external("env", "Rml_LoadDocumentFromMemory")
export declare function rawRml_LoadDocumentFromMemory(ctx: i32, rml: string, source_url: string): i32;

@external("env", "Rml_LoadDocumentFromBuffer")
export declare function rawRml_LoadDocumentFromBuffer(ctx: i32, data: i32, len: i32): i32;

@external("env", "Rml_ShowDocument")
export declare function rawRml_ShowDocument(doc: i32): void;

@external("env", "Rml_HideDocument")
export declare function rawRml_HideDocument(doc: i32): void;

@external("env", "Rml_CloseDocument")
export declare function rawRml_CloseDocument(doc: i32): void;

@external("env", "Rml_GetNumDocuments")
export declare function rawRml_GetNumDocuments(ctx: i32): i32;

@external("env", "Rml_GetDocument")
export declare function rawRml_GetDocument(ctx: i32, index: i32): i32;

@external("env", "Rml_CreateElement")
export declare function rawRml_CreateElement(tag: string): i32;

@external("env", "Rml_CreateTextNode")
export declare function rawRml_CreateTextNode(text: string): i32;

@external("env", "Rml_AppendChild")
export declare function rawRml_AppendChild(parent: i32, child: i32): i32;

@external("env", "Rml_RemoveChild")
export declare function rawRml_RemoveChild(parent: i32, child: i32): i32;

@external("env", "Rml_InsertBefore")
export declare function rawRml_InsertBefore(parent: i32, child: i32, ref: i32): i32;

@external("env", "Rml_ReplaceChild")
export declare function rawRml_ReplaceChild(parent: i32, newChild: i32, oldChild: i32): i32;

@external("env", "Rml_SetAttribute")
export declare function rawRml_SetAttribute(el: i32, name: string, value: string): i32;

@external("env", "Rml_GetAttribute")
export declare function rawRml_GetAttribute(el: i32, name: string): string;

@external("env", "Rml_RemoveAttribute")
export declare function rawRml_RemoveAttribute(el: i32, name: string): i32;

@external("env", "Rml_HasAttribute")
export declare function rawRml_HasAttribute(el: i32, name: string): i32;

@external("env", "Rml_SetTextContent")
export declare function rawRml_SetTextContent(el: i32, text: string): i32;

@external("env", "Rml_GetTextContent")
export declare function rawRml_GetTextContent(el: i32): string;

@external("env", "Rml_SetInnerHTML")
export declare function rawRml_SetInnerHTML(el: i32, html: string): i32;

@external("env", "Rml_GetInnerHTML")
export declare function rawRml_GetInnerHTML(el: i32): string;

@external("env", "Rml_SetStyleProperty")
export declare function rawRml_SetStyleProperty(el: i32, prop: string, value: string): i32;

@external("env", "Rml_GetStyleProperty")
export declare function rawRml_GetStyleProperty(el: i32, prop: string): string;

@external("env", "Rml_SetStyle")
export declare function rawRml_SetStyle(el: i32, css_text: string): i32;

@external("env", "Rml_AddEventListener")
export declare function rawRml_AddEventListener(el: i32, event: string, cb_id: i32): i32;

@external("env", "Rml_RemoveEventListener")
export declare function rawRml_RemoveEventListener(el: i32, event: string): i32;

@external("env", "Rml_GetCurrentEvent")
export declare function rawRml_GetCurrentEvent(): i32;

@external("env", "Rml_SetClass")
export declare function rawRml_SetClass(el: i32, cls: string, enabled: i32): i32;

@external("env", "Rml_IsClassSet")
export declare function rawRml_IsClassSet(el: i32, cls: string): i32;

@external("env", "Rml_SetClassNames")
export declare function rawRml_SetClassNames(el: i32, names: string): i32;

@external("env", "Rml_LoadFont")
export declare function rawRml_LoadFont(path: string): i32;

@external("env", "Rml_LoadFontFromBuffer")
export declare function rawRml_LoadFontFromBuffer(name: string, data: i32, len: i32): i32;

@external("env", "Rml_LoadTexture")
export declare function rawRml_LoadTexture(path: string): i32;

@external("env", "Rml_LoadTextureFromBuffer")
export declare function rawRml_LoadTextureFromBuffer(name: string, data: i32, len: i32): i32;

@external("env", "Rml_GetTextureDimensions")
export declare function rawRml_GetTextureDimensions(name: string, w: i32, h: i32): i32;

@external("env", "RmlUI_ProcessSdlEvents")
export declare function rawRmlUI_ProcessSdlEvents(): void;

@external("env", "RmlUI_Update")
export declare function rawRmlUI_Update(): void;

@external("env", "RmlUI_Render")
export declare function rawRmlUI_Render(): void;

@external("env", "RmlUI_Shutdown")
export declare function rawRmlUI_Shutdown(): void;

@external("env", "RmlUI_IsRunning")
export declare function rawRmlUI_IsRunning(): i32;

@external("env", "Rml_GetElementById")
export declare function rawRml_GetElementById(ctx: i32, id: string): i32;

@external("env", "Rml_QuerySelector")
export declare function rawRml_QuerySelector(el: i32, selector: string): i32;

@external("env", "Rml_QuerySelectorAll")
export declare function rawRml_QuerySelectorAll(el: i32, selector: string): i32;

@external("env", "Rml_FreeNodeList")
export declare function rawRml_FreeNodeList(elements: i32): void;

@external("env", "Rml_GetBody")
export declare function rawRml_GetBody(ctx: i32): i32;

@external("env", "Rml_GetHead")
export declare function rawRml_GetHead(ctx: i32): i32;

@external("env", "Rml_SetResourcePath")
export declare function rawRml_SetResourcePath(ctx: i32, path_list: string): i32;

@external("env", "Rml_RegisterResourceProvider")
export declare function rawRml_RegisterResourceProvider(ctx: i32, provider: i32): i32;

@external("env", "Rml_DebuggerToggle")
export declare function rawRml_DebuggerToggle(): void;

// ── TypeScript/AssemblyScript Wrappers ─────────────────────────────

// Error codes matching rmlui-abi.h
export const RMLUI_OK: i32 = 0;
export const RMLUI_ERR_INVALID_HANDLE: i32 = -1;
export const RMLUI_ERR_NULL_PARAM: i32 = -2;
export const RMLUI_ERR_OUT_OF_MEMORY: i32 = -3;
export const RMLUI_ERR_UNSUPPORTED: i32 = -4;
export const RMLUI_ERR_INTERNAL: i32 = -5;

/** Safe wrapper around `Rml_CreateContext`. */
export function createContext(name: string, w: i32, h: i32): i32 {
  const result = rawRml_CreateContext(name, w, h);
  if (result < 0) {
    // Caller should check return value
    return result;
  }
  return result;
}

/** Safe wrapper around `Rml_ReleaseContext`. */
export function releaseContext(ctx: i32): void {
  rawRml_ReleaseContext(ctx);
}

/** Safe wrapper around `Rml_LoadDocument`. */
export function loadDocument(ctx: i32, path: string): i32 {
  const result = rawRml_LoadDocument(ctx, path);
  if (result < 0) {
    // Caller should check return value
    return result;
  }
  return result;
}

/** Safe wrapper around `Rml_LoadDocumentFromMemory`. */
export function loadDocumentFromMemory(ctx: i32, rml: string, source_url: string): i32 {
  const result = rawRml_LoadDocumentFromMemory(ctx, rml, source_url);
  if (result < 0) {
    // Caller should check return value
    return result;
  }
  return result;
}

/** Safe wrapper around `Rml_LoadDocumentFromBuffer`. */
export function loadDocumentFromBuffer(ctx: i32, data: i32, len: i32): i32 {
  const result = rawRml_LoadDocumentFromBuffer(ctx, data, len);
  if (result < 0) {
    // Caller should check return value
    return result;
  }
  return result;
}

/** Safe wrapper around `Rml_ShowDocument`. */
export function showDocument(doc: i32): void {
  rawRml_ShowDocument(doc);
}

/** Safe wrapper around `Rml_HideDocument`. */
export function hideDocument(doc: i32): void {
  rawRml_HideDocument(doc);
}

/** Safe wrapper around `Rml_CloseDocument`. */
export function closeDocument(doc: i32): void {
  rawRml_CloseDocument(doc);
}

/** Safe wrapper around `Rml_GetNumDocuments`. */
export function getNumDocuments(ctx: i32): i32 {
  const result = rawRml_GetNumDocuments(ctx);
  if (result < 0) {
    // Caller should check return value
    return result;
  }
  return result;
}

/** Safe wrapper around `Rml_GetDocument`. */
export function getDocument(ctx: i32, index: i32): i32 {
  const result = rawRml_GetDocument(ctx, index);
  if (result < 0) {
    // Caller should check return value
    return result;
  }
  return result;
}

/** Safe wrapper around `Rml_CreateElement`. */
export function createElement(tag: string): i32 {
  const result = rawRml_CreateElement(tag);
  if (result < 0) {
    // Caller should check return value
    return result;
  }
  return result;
}

/** Safe wrapper around `Rml_CreateTextNode`. */
export function createTextNode(text: string): i32 {
  const result = rawRml_CreateTextNode(text);
  if (result < 0) {
    // Caller should check return value
    return result;
  }
  return result;
}

/** Safe wrapper around `Rml_AppendChild`. */
export function appendChild(parent: i32, child: i32): i32 {
  const result = rawRml_AppendChild(parent, child);
  if (result < 0) {
    // Caller should check return value
    return result;
  }
  return result;
}

/** Safe wrapper around `Rml_RemoveChild`. */
export function removeChild(parent: i32, child: i32): i32 {
  const result = rawRml_RemoveChild(parent, child);
  if (result < 0) {
    // Caller should check return value
    return result;
  }
  return result;
}

/** Safe wrapper around `Rml_InsertBefore`. */
export function insertBefore(parent: i32, child: i32, ref: i32): i32 {
  const result = rawRml_InsertBefore(parent, child, ref);
  if (result < 0) {
    // Caller should check return value
    return result;
  }
  return result;
}

/** Safe wrapper around `Rml_ReplaceChild`. */
export function replaceChild(parent: i32, newChild: i32, oldChild: i32): i32 {
  const result = rawRml_ReplaceChild(parent, newChild, oldChild);
  if (result < 0) {
    // Caller should check return value
    return result;
  }
  return result;
}

/** Safe wrapper around `Rml_SetAttribute`. */
export function setAttribute(el: i32, name: string, value: string): i32 {
  const result = rawRml_SetAttribute(el, name, value);
  if (result < 0) {
    // Caller should check return value
    return result;
  }
  return result;
}

/** Safe wrapper around `Rml_GetAttribute`. */
export function getAttribute(el: i32, name: string): string {
  const ptr = rawRml_GetAttribute(el, name);
  if (ptr === 0) return '';
  // Read null-terminated string from WASM memory at ptr
  let result = '';
  let i = ptr;
  while (load<u8>(i) !== 0) {
    result += String.fromCharCode(load<u8>(i));
    i++;
  }
  return result;
}

/** Safe wrapper around `Rml_RemoveAttribute`. */
export function removeAttribute(el: i32, name: string): i32 {
  const result = rawRml_RemoveAttribute(el, name);
  if (result < 0) {
    // Caller should check return value
    return result;
  }
  return result;
}

/** Safe wrapper around `Rml_HasAttribute`. */
export function hasAttribute(el: i32, name: string): i32 {
  const result = rawRml_HasAttribute(el, name);
  if (result < 0) {
    // Caller should check return value
    return result;
  }
  return result;
}

/** Safe wrapper around `Rml_SetTextContent`. */
export function setTextContent(el: i32, text: string): i32 {
  const result = rawRml_SetTextContent(el, text);
  if (result < 0) {
    // Caller should check return value
    return result;
  }
  return result;
}

/** Safe wrapper around `Rml_GetTextContent`. */
export function getTextContent(el: i32): string {
  const ptr = rawRml_GetTextContent(el);
  if (ptr === 0) return '';
  // Read null-terminated string from WASM memory at ptr
  let result = '';
  let i = ptr;
  while (load<u8>(i) !== 0) {
    result += String.fromCharCode(load<u8>(i));
    i++;
  }
  return result;
}

/** Safe wrapper around `Rml_SetInnerHTML`. */
export function setInnerHTML(el: i32, html: string): i32 {
  const result = rawRml_SetInnerHTML(el, html);
  if (result < 0) {
    // Caller should check return value
    return result;
  }
  return result;
}

/** Safe wrapper around `Rml_GetInnerHTML`. */
export function getInnerHTML(el: i32): string {
  const ptr = rawRml_GetInnerHTML(el);
  if (ptr === 0) return '';
  // Read null-terminated string from WASM memory at ptr
  let result = '';
  let i = ptr;
  while (load<u8>(i) !== 0) {
    result += String.fromCharCode(load<u8>(i));
    i++;
  }
  return result;
}

/** Safe wrapper around `Rml_SetStyleProperty`. */
export function setStyleProperty(el: i32, prop: string, value: string): i32 {
  const result = rawRml_SetStyleProperty(el, prop, value);
  if (result < 0) {
    // Caller should check return value
    return result;
  }
  return result;
}

/** Safe wrapper around `Rml_GetStyleProperty`. */
export function getStyleProperty(el: i32, prop: string): string {
  const ptr = rawRml_GetStyleProperty(el, prop);
  if (ptr === 0) return '';
  // Read null-terminated string from WASM memory at ptr
  let result = '';
  let i = ptr;
  while (load<u8>(i) !== 0) {
    result += String.fromCharCode(load<u8>(i));
    i++;
  }
  return result;
}

/** Safe wrapper around `Rml_SetStyle`. */
export function setStyle(el: i32, css_text: string): i32 {
  const result = rawRml_SetStyle(el, css_text);
  if (result < 0) {
    // Caller should check return value
    return result;
  }
  return result;
}

/** Safe wrapper around `Rml_AddEventListener`. */
export function addEventListener(el: i32, event: string, cb_id: i32): i32 {
  const result = rawRml_AddEventListener(el, event, cb_id);
  if (result < 0) {
    // Caller should check return value
    return result;
  }
  return result;
}

/** Safe wrapper around `Rml_RemoveEventListener`. */
export function removeEventListener(el: i32, event: string): i32 {
  const result = rawRml_RemoveEventListener(el, event);
  if (result < 0) {
    // Caller should check return value
    return result;
  }
  return result;
}

/** Safe wrapper around `Rml_GetCurrentEvent`. */
export function getCurrentEvent(): i32 {
  const result = rawRml_GetCurrentEvent();
  if (result < 0) {
    // Caller should check return value
    return result;
  }
  return result;
}

/** Safe wrapper around `Rml_SetClass`. */
export function setClass(el: i32, cls: string, enabled: i32): i32 {
  const result = rawRml_SetClass(el, cls, enabled);
  if (result < 0) {
    // Caller should check return value
    return result;
  }
  return result;
}

/** Safe wrapper around `Rml_IsClassSet`. */
export function isClassSet(el: i32, cls: string): i32 {
  const result = rawRml_IsClassSet(el, cls);
  if (result < 0) {
    // Caller should check return value
    return result;
  }
  return result;
}

/** Safe wrapper around `Rml_SetClassNames`. */
export function setClassNames(el: i32, names: string): i32 {
  const result = rawRml_SetClassNames(el, names);
  if (result < 0) {
    // Caller should check return value
    return result;
  }
  return result;
}

/** Safe wrapper around `Rml_LoadFont`. */
export function loadFont(path: string): i32 {
  const result = rawRml_LoadFont(path);
  if (result < 0) {
    // Caller should check return value
    return result;
  }
  return result;
}

/** Safe wrapper around `Rml_LoadFontFromBuffer`. */
export function loadFontFromBuffer(name: string, data: i32, len: i32): i32 {
  const result = rawRml_LoadFontFromBuffer(name, data, len);
  if (result < 0) {
    // Caller should check return value
    return result;
  }
  return result;
}

/** Safe wrapper around `Rml_LoadTexture`. */
export function loadTexture(path: string): i32 {
  const result = rawRml_LoadTexture(path);
  if (result < 0) {
    // Caller should check return value
    return result;
  }
  return result;
}

/** Safe wrapper around `Rml_LoadTextureFromBuffer`. */
export function loadTextureFromBuffer(name: string, data: i32, len: i32): i32 {
  const result = rawRml_LoadTextureFromBuffer(name, data, len);
  if (result < 0) {
    // Caller should check return value
    return result;
  }
  return result;
}

/** Safe wrapper around `Rml_GetTextureDimensions`. */
export function getTextureDimensions(name: string, w: i32, h: i32): i32 {
  const result = rawRml_GetTextureDimensions(name, w, h);
  if (result < 0) {
    // Caller should check return value
    return result;
  }
  return result;
}

/** Safe wrapper around `RmlUI_ProcessSdlEvents`. */
export function processSdlEvents(): void {
  rawRmlUI_ProcessSdlEvents();
}

/** Safe wrapper around `RmlUI_Update`. */
export function update(): void {
  rawRmlUI_Update();
}

/** Safe wrapper around `RmlUI_Render`. */
export function render(): void {
  rawRmlUI_Render();
}

/** Safe wrapper around `RmlUI_Shutdown`. */
export function shutdown(): void {
  rawRmlUI_Shutdown();
}

/** Safe wrapper around `RmlUI_IsRunning`. */
export function isRunning(): i32 {
  const result = rawRmlUI_IsRunning();
  if (result < 0) {
    // Caller should check return value
    return result;
  }
  return result;
}

/** Safe wrapper around `Rml_GetElementById`. */
export function getElementById(ctx: i32, id: string): i32 {
  const result = rawRml_GetElementById(ctx, id);
  if (result < 0) {
    // Caller should check return value
    return result;
  }
  return result;
}

/** Safe wrapper around `Rml_QuerySelector`. */
export function querySelector(el: i32, selector: string): i32 {
  const result = rawRml_QuerySelector(el, selector);
  if (result < 0) {
    // Caller should check return value
    return result;
  }
  return result;
}

/** Safe wrapper around `Rml_QuerySelectorAll`. */
export function querySelectorAll(el: i32, selector: string): i32 {
  const result = rawRml_QuerySelectorAll(el, selector);
  if (result < 0) {
    // Caller should check return value
    return result;
  }
  return result;
}

/** Safe wrapper around `Rml_FreeNodeList`. */
export function freeNodeList(elements: i32): void {
  rawRml_FreeNodeList(elements);
}

/** Safe wrapper around `Rml_GetBody`. */
export function getBody(ctx: i32): i32 {
  const result = rawRml_GetBody(ctx);
  if (result < 0) {
    // Caller should check return value
    return result;
  }
  return result;
}

/** Safe wrapper around `Rml_GetHead`. */
export function getHead(ctx: i32): i32 {
  const result = rawRml_GetHead(ctx);
  if (result < 0) {
    // Caller should check return value
    return result;
  }
  return result;
}

/** Safe wrapper around `Rml_SetResourcePath`. */
export function setResourcePath(ctx: i32, path_list: string): i32 {
  const result = rawRml_SetResourcePath(ctx, path_list);
  if (result < 0) {
    // Caller should check return value
    return result;
  }
  return result;
}

/** Safe wrapper around `Rml_RegisterResourceProvider`. */
export function registerResourceProvider(ctx: i32, provider: i32): i32 {
  const result = rawRml_RegisterResourceProvider(ctx, provider);
  if (result < 0) {
    // Caller should check return value
    return result;
  }
  return result;
}

/** Safe wrapper around `Rml_DebuggerToggle`. */
export function debuggerToggle(): void {
  rawRml_DebuggerToggle();
}

// ── Element class ─────────────────────────────────────────────────────
export class Element {
  constructor(public id: i32) {}

  // Child management
  appendChild(child: Element): Element {
    const result = rawRml_AppendChild(this.id, child.id);
    if (result < 0) throw new Error('RmlUI error: ' + result.toString());
    return child;
  }

  removeChild(child: Element): void {
    const result = rawRml_RemoveChild(this.id, child.id);
    if (result < 0) throw new Error('RmlUI error: ' + result.toString());
  }

  insertBefore(child: Element, ref: Element): void {
    const result = rawRml_InsertBefore(this.id, child.id, ref.id);
    if (result < 0) throw new Error('RmlUI error: ' + result.toString());
  }

  replaceChild(newChild: Element, oldChild: Element): void {
    const result = rawRml_ReplaceChild(this.id, newChild.id, oldChild.id);
    if (result < 0) throw new Error('RmlUI error: ' + result.toString());
  }

  // Attributes
  setAttribute(name: string, value: string): void {
    const result = rawRml_SetAttribute(this.id, name, value);
    if (result < 0) throw new Error('RmlUI error: ' + result.toString());
  }

  getAttribute(name: string): string {
    return rawRml_GetAttribute(this.id, name);
  }

  removeAttribute(name: string): void {
    const result = rawRml_RemoveAttribute(this.id, name);
    if (result < 0) throw new Error('RmlUI error: ' + result.toString());
  }

  hasAttribute(name: string): bool {
    return rawRml_HasAttribute(this.id, name) > 0;
  }

  // Content
  set textContent(text: string) {
    const result = rawRml_SetTextContent(this.id, text);
    if (result < 0) throw new Error('RmlUI error: ' + result.toString());
  }

  get textContent(): string {
    return rawRml_GetTextContent(this.id);
  }

  set innerHTML(html: string) {
    const result = rawRml_SetInnerHTML(this.id, html);
    if (result < 0) throw new Error('RmlUI error: ' + result.toString());
  }

  get innerHTML(): string {
    return rawRml_GetInnerHTML(this.id);
  }

  // Style
  setStyleProperty(prop: string, value: string): void {
    const result = rawRml_SetStyleProperty(this.id, prop, value);
    if (result < 0) throw new Error('RmlUI error: ' + result.toString());
  }

  getStyleProperty(prop: string): string {
    return rawRml_GetStyleProperty(this.id, prop);
  }

  setStyle(css: string): void {
    const result = rawRml_SetStyle(this.id, css);
    if (result < 0) throw new Error('RmlUI error: ' + result.toString());
  }

  // Events
  addEventListener(event: string, cb_id: i32): void {
    const result = rawRml_AddEventListener(this.id, event, cb_id);
    if (result < 0) throw new Error('RmlUI error: ' + result.toString());
  }

  removeEventListener(event: string): void {
    const result = rawRml_RemoveEventListener(this.id, event);
    if (result < 0) throw new Error('RmlUI error: ' + result.toString());
  }

  // Class list
  setClass(cls: string, enabled: bool): void {
    const result = rawRml_SetClass(this.id, cls, enabled ? 1 : 0);
    if (result < 0) throw new Error('RmlUI error: ' + result.toString());
  }

  isClassSet(cls: string): bool {
    return rawRml_IsClassSet(this.id, cls) > 0;
  }

  setClassNames(names: string): void {
    const result = rawRml_SetClassNames(this.id, names);
    if (result < 0) throw new Error('RmlUI error: ' + result.toString());
  }

  addClass(cls: string): void {
    this.setClass(cls, true);
  }

  removeClass(cls: string): void {
    this.setClass(cls, false);
  }

  toggleClass(cls: string): void {
    this.setClass(cls, !this.isClassSet(cls));
  }

  hasClass(cls: string): bool {
    return this.isClassSet(cls);
  }

  // Query
  querySelector(selector: string): Element | null {
    const result = rawRml_QuerySelector(this.id, selector);
    if (result <= 0) return null;
    return new Element(result);
  }

  querySelectorAll(selector: string): Element[] {
    const ptr = rawRml_QuerySelectorAll(this.id, selector);
    if (ptr <= 0) return [];
    const result: Element[] = [];
    let i = ptr;
    while (load<i32>(i) !== 0) {
      result.push(new Element(load<i32>(i)));
      i += 4;
    }
    rawRml_FreeNodeList(ptr);
    return result;
  }
}

// ── Document class ────────────────────────────────────────────────────
export class Document {
  constructor(
    public ctx: i32,
    public docId: i32,
  ) {}

  get body(): Element | null {
    const result = rawRml_GetBody(this.ctx);
    if (result <= 0) return null;
    return new Element(result);
  }

  get head(): Element | null {
    const result = rawRml_GetHead(this.ctx);
    if (result <= 0) return null;
    return new Element(result);
  }

  getElementById(id: string): Element | null {
    const result = rawRml_GetElementById(this.ctx, id);
    if (result <= 0) return null;
    return new Element(result);
  }

  createElement(tag: string): Element {
    const result = rawRml_CreateElement(tag);
    if (result < 0) throw new Error('RmlUI error: ' + result.toString());
    return new Element(result);
  }

  createTextNode(text: string): Element {
    const result = rawRml_CreateTextNode(text);
    if (result < 0) throw new Error('RmlUI error: ' + result.toString());
    return new Element(result);
  }

  show(): void {
    rawRml_ShowDocument(this.docId);
  }

  hide(): void {
    rawRml_HideDocument(this.docId);
  }

  close(): void {
    rawRml_CloseDocument(this.docId);
  }

  querySelector(selector: string): Element | null {
    // Query from body
    const body = this.body;
    if (!body) return null;
    return body.querySelector(selector);
  }
}
